/**
 * AIInsights — Phase 3 (ML-powered)
 *
 * The same component now optionally renders:
 *  - SHAP-driven insight cards (with feature value + contribution magnitude)
 *  - Anomaly alert card (when today is flagged as unusual)
 *  - Cluster archetype badge (when ML has assigned an archetype)
 *  - Falls back to plain insights when ML data isn't present (cold-start users)
 */

export default function AIInsights({ insights, metadata, anomaly, cluster }) {
    if (!insights || insights.length === 0) return null;

    const iconMap = {
        positive:   '↗',
        warning:    '!',
        suggestion: '◆',
    };
    const colorMap = {
        positive:   '#34D399',
        warning:    '#FB923C',
        suggestion: '#0BEFC4',
    };

    const usingML = metadata?.modelSource?.startsWith('ml-');

    return (
        <div className="ai-insights">
            <div className="ai-insights__header">
                <div>
                    <p className="ai-insights__eyebrow">
                        {usingML ? 'AI Analysis · Personalized' : 'Analysis · Rule-based'}
                    </p>
                    <h3 className="ai-insights__title">Insights</h3>
                </div>

                <div className="ai-insights__meta-stack">
                    {metadata?.daysAnalyzed && (
                        <span className="ai-insights__meta">
                            Based on {metadata.daysAnalyzed} days
                        </span>
                    )}
                    {usingML && (
                        <span className="ai-insights__badge ai-insights__badge--ml">
                            ML
                        </span>
                    )}
                    {metadata?.modelSource === 'rule-based-fallback' && (
                        <span className="ai-insights__badge ai-insights__badge--fallback">
                            FALLBACK
                        </span>
                    )}
                </div>
            </div>

            {/* Anomaly alert — only shown when ML flags today as unusual */}
            {anomaly?.is_anomaly && (
                <div className="ai-anomaly-card">
                    <span className="ai-anomaly-card__icon">⚠</span>
                    <div className="ai-anomaly-card__body">
                        <p className="ai-anomaly-card__title">Unusual day detected</p>
                        <p className="ai-anomaly-card__text">{anomaly.interpretation}</p>
                        <p className="ai-anomaly-card__meta">
                            Based on {anomaly.days_in_history} days of your history
                            · score {anomaly.anomaly_score}
                        </p>
                    </div>
                </div>
            )}

            {/* Cluster archetype badge — only shown when ML assigned one */}
            {cluster?.archetype_label && (
                <div className="ai-cluster-card">
                    <span className="ai-cluster-card__label">YOUR PROFILE</span>
                    <span className="ai-cluster-card__archetype">{cluster.archetype_label}</span>
                    <span className="ai-cluster-card__match">
                        {Math.round((cluster.silhouette_match || 0) * 100)}% match
                    </span>
                </div>
            )}

            {/* Insight cards */}
            <div className="ai-insights__list">
                {insights.map((insight, i) => (
                    <div
                        key={i}
                        className={`ai-insight ai-insight--${insight.type}`}
                        style={{ borderLeftColor: colorMap[insight.type] }}
                    >
                        <span
                            className="ai-insight__icon"
                            style={{
                                color: colorMap[insight.type],
                                background: `${colorMap[insight.type]}15`,
                            }}
                        >
                            {iconMap[insight.type]}
                        </span>
                        <div className="ai-insight__body">
                            <span className="ai-insight__category">{insight.category}</span>
                            <p className="ai-insight__text">{insight.text}</p>
                        </div>
                    </div>
                ))}
            </div>

            {/* Footer with model attribution */}
            <div className="ai-insights__footer">
                {usingML ? (
                    <p className="ai-insights__attribution">
                        Generated by XGBoost personalized model with SHAP explainability ·
                        trained on real LifeSnaps data
                    </p>
                ) : (
                    <p className="ai-insights__attribution">
                        Cold-start mode — switching to ML after 14 days of data
                    </p>
                )}
            </div>
        </div>
    );
}
