import { useEffect, useState } from 'react';
import axios from 'axios';
import { API_BASE_URL } from '../../../config/api';
import InfoTooltip from './InfoTooltip';
import './AISummary.css';

/**
 * AI Summary section. Renders the wellness-coach narrative at the bottom of
 * either the Physical or Mental tab.
 *
 * Props:
 *   - type:   'physical' | 'mental'
 *   - accent: optional override of accent color (defaults: teal physical, violet mental)
 */
export default function AISummary({ type, accent }) {
    const [state, setState] = useState({ loading: true, content: null, error: null, meta: null });

    useEffect(() => {
        let cancelled = false;
        const fetchSummary = async () => {
            try {
                const token = localStorage.getItem('moodlens.token');
                const res = await axios.get(`${API_BASE_URL}/api/ai/summary/${type}`, {
                    headers: { Authorization: `Bearer ${token}` },
                    timeout: 25000,
                });
                if (cancelled) return;

                if (res.data?.error) {
                    setState({ loading: false, content: null, error: res.data, meta: null });
                } else {
                    setState({
                        loading: false,
                        content: res.data.content,
                        error: null,
                        meta: { cached: res.data.cached, generatedAt: res.data.generatedAt },
                    });
                }
            } catch (err) {
                if (cancelled) return;
                setState({
                    loading: false,
                    content: null,
                    error: { message: err.response?.data?.message || 'Could not load summary.' },
                    meta: null,
                });
            }
        };
        fetchSummary();
        return () => { cancelled = true; };
    }, [type]);

    const accentClass = accent || (type === 'physical' ? 'teal' : 'violet');
    const titleWord = type === 'physical' ? 'Physical' : 'Mental';

    return (
        <section className={`ai-summary ai-summary--${accentClass}`}>
            <header className="ai-summary__head">
                <div className="ai-summary__heading">
                    <p className="ai-summary__eyebrow">AI Coach</p>
                    <div className="ai-summary__title-row">
                        <h2 className="ai-summary__title">Your {titleWord} Summary</h2>
                        <InfoTooltip
                            what={`A 4-paragraph wellness-coach style summary of your ${type} health, generated by AI from your data.`}
                            how="Read top to bottom: what's working, what needs attention, why it matters, and one specific thing to try this week."
                            why="The charts above show numbers; this section translates them into plain language and a concrete action."
                        />
                    </div>
                </div>
                {state.meta && (
                    <span className="ai-summary__meta">
                        {state.meta.cached ? 'Cached' : 'Fresh'}
                    </span>
                )}
            </header>

            <div className="ai-summary__body">
                {state.loading && (
                    <div className="ai-summary__loading">
                        <div className="ai-summary__skeleton" />
                        <div className="ai-summary__skeleton" />
                        <div className="ai-summary__skeleton ai-summary__skeleton--short" />
                        <p className="ai-summary__loading-text">
                            Your AI coach is reading through your data…
                        </p>
                    </div>
                )}

                {state.error && (
                    <div className="ai-summary__error">
                        <p className="ai-summary__error-title">
                            {state.error.error === 'NO_DATA' || state.error.error === 'NO_ASSESSMENT'
                                ? 'Not enough data yet'
                                : 'Summary unavailable'}
                        </p>
                        <p className="ai-summary__error-msg">{state.error.message}</p>
                    </div>
                )}

                {state.content && (
                    <div className="ai-summary__content">
                        {splitParagraphs(state.content).map((para, i) => (
                            <p key={i} className="ai-summary__paragraph">{para}</p>
                        ))}
                    </div>
                )}
            </div>

            <footer className="ai-summary__foot">
                <p className="ai-summary__disclaimer">
                    This summary is for informational purposes only and is not medical advice.
                    If you are experiencing distress, please reach out to a qualified professional.
                </p>
            </footer>
        </section>
    );
}

/**
 * Split the LLM output into paragraphs. Strip any markdown the model might
 * have slipped in despite instructions (headings, bullets, bold/italic).
 */
function splitParagraphs(content) {
    return content
        .split(/\n\s*\n/)                        // double newline = paragraph break
        .map(p => p.trim())
        .map(p => p.replace(/^#+\s*/gm, ''))     // strip markdown headings
        .map(p => p.replace(/^\s*[-*]\s+/gm, '')) // strip bullets
        .map(p => p.replace(/\*\*(.*?)\*\*/g, '$1'))  // strip bold
        .map(p => p.replace(/\*(.*?)\*/g, '$1'))      // strip italic
        .map(p => p.replace(/^Paragraph \d+[:\s—-]*/i, '')) // strip "Paragraph 1:" if model left it
        .filter(p => p.length > 0);
}
